service: sb-email-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 300 # 5 minutes for email generation
  environment:
    NODE_ENV: ${self:provider.stage}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    BRANDDEV_API_KEY: ${env:BRANDDEV_API_KEY, ''}
    S3_REGION: ${env:S3_REGION, ''}
    S3_ACCESS_KEY_ID: ${env:S3_ACCESS_KEY_ID, ''}
    S3_SECRET_ACCESS_KEY: ${env:S3_SECRET_ACCESS_KEY, ''}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, ''}
    SUPABASE_URL: ${env:SUPABASE_URL, ''}
    SUPABASE_SERVICE_KEY: ${env:SUPABASE_SERVICE_KEY, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: 
            - "arn:aws:s3:::${env:S3_BUCKET_NAME, '*'}/hero_images/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - route53:GetHostedZone
            - route53:ChangeResourceRecordSets
            - route53:ListResourceRecordSets
          Resource: 
            - "arn:aws:route53:::hostedzone/*"

custom:
  customDomain:
    domainName: mjml-generator-service.springbot.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    createRoute53IPv6Record: false
    endpointType: 'regional'
    securityPolicy: tls_1_2
    autoDomain: true
    autoDomainWaitFor: 120

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: GET
          cors: true
    environment:
      FUNCTION_NAME: ${self:service}-${self:provider.stage}

plugins:
  - serverless-domain-manager

package:
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/@prisma/client/libquery_engine-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!scripts/**'
    - '!test-data/**'
    - '!public/**'
    - '!.env*'
    - '!amplify.yml'
    - '!README.md'
    - '!.git/**' 